-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action_type text NOT NULL,
  entity_id uuid,
  details text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  ip_address text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT activity_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  label text NOT NULL,
  street text NOT NULL,
  city text NOT NULL DEFAULT 'Dar es Salaam'::text,
  postal_code text,
  landmark text,
  latitude numeric,
  longitude numeric,
  phone text NOT NULL,
  is_default boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone,
  deleted_at timestamp with time zone,
  CONSTRAINT addresses_pkey PRIMARY KEY (id),
  CONSTRAINT addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.cart_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cart_id uuid NOT NULL,
  product_id uuid NOT NULL,
  variant_id uuid,
  quantity integer NOT NULL CHECK (quantity > 0),
  price_at_add numeric NOT NULL CHECK (price_at_add >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT cart_items_pkey PRIMARY KEY (id),
  CONSTRAINT cart_items_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES public.carts(id),
  CONSTRAINT cart_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT cart_items_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(id)
);
CREATE TABLE public.carts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT carts_pkey PRIMARY KEY (id),
  CONSTRAINT carts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  parent_id uuid,
  icon_url text,
  image_url text,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone,
  deleted_at timestamp with time zone,
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.categories(id)
);
CREATE TABLE public.dispute_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  dispute_id uuid NOT NULL,
  changed_by uuid,
  from_status text,
  to_status text NOT NULL,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT dispute_events_pkey PRIMARY KEY (id),
  CONSTRAINT dispute_events_dispute_id_fkey FOREIGN KEY (dispute_id) REFERENCES public.disputes(id),
  CONSTRAINT dispute_events_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.dispute_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  dispute_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  body text NOT NULL,
  attachments ARRAY NOT NULL DEFAULT '{}'::text[],
  is_internal boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT dispute_messages_pkey PRIMARY KEY (id),
  CONSTRAINT dispute_messages_dispute_id_fkey FOREIGN KEY (dispute_id) REFERENCES public.disputes(id),
  CONSTRAINT dispute_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.disputes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  order_item_id uuid,
  fulfillment_id uuid,
  buyer_id uuid NOT NULL,
  seller_id uuid NOT NULL,
  assigned_to uuid,
  reason text NOT NULL,
  status text NOT NULL DEFAULT 'open',
  description text NOT NULL,
  evidence_urls ARRAY NOT NULL DEFAULT '{}'::text[],
  resolution_notes text,
  refund_amount numeric DEFAULT 0 CHECK (refund_amount >= 0::numeric),
  resolved_at timestamp with time zone,
  resolution_deadline timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT disputes_pkey PRIMARY KEY (id),
  CONSTRAINT disputes_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT disputes_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id),
  CONSTRAINT disputes_fulfillment_id_fkey FOREIGN KEY (fulfillment_id) REFERENCES public.fulfillments(id),
  CONSTRAINT disputes_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES public.profiles(id),
  CONSTRAINT disputes_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.profiles(id),
  CONSTRAINT disputes_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(id)
);
CREATE TABLE public.fulfillments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  seller_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  subtotal numeric NOT NULL DEFAULT 0 CHECK (subtotal >= 0::numeric),
  discount_amount numeric NOT NULL DEFAULT 0 CHECK (discount_amount >= 0::numeric),
  delivery_fee numeric NOT NULL DEFAULT 0 CHECK (delivery_fee >= 0::numeric),
  vat_amount numeric NOT NULL DEFAULT 0 CHECK (vat_amount >= 0::numeric),
  total numeric NOT NULL DEFAULT 0 CHECK (total >= 0::numeric),
  commission_rate numeric NOT NULL DEFAULT 0 CHECK (commission_rate >= 0::numeric AND commission_rate <= 1::numeric),
  commission_amount numeric NOT NULL DEFAULT 0,
  net_payout numeric NOT NULL DEFAULT 0,
  payout_id uuid,
  seller_notes text,
  admin_notes text,
  cancel_reason text,
  confirmed_at timestamp with time zone,
  shipped_at timestamp with time zone,
  delivered_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fulfillments_pkey PRIMARY KEY (id),
  CONSTRAINT fulfillments_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT fulfillments_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.profiles(id),
  CONSTRAINT fulfillments_payout_id_fkey FOREIGN KEY (payout_id) REFERENCES public.seller_payouts(id)
);
CREATE TABLE public.inventory_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  variant_id uuid,
  reason text NOT NULL,
  delta integer NOT NULL,
  stock_before integer NOT NULL,
  stock_after integer NOT NULL,
  order_id uuid,
  order_item_id uuid,
  return_id uuid,
  performed_by uuid,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT inventory_logs_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_logs_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT inventory_logs_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(id),
  CONSTRAINT inventory_logs_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT inventory_logs_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id),
  CONSTRAINT inventory_logs_return_id_fkey FOREIGN KEY (return_id) REFERENCES public.returns(id),
  CONSTRAINT inventory_logs_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sender_id uuid NOT NULL,
  receiver_id uuid NOT NULL,
  product_id uuid,
  body text NOT NULL,
  read boolean NOT NULL DEFAULT false,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES public.profiles(id),
  CONSTRAINT messages_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  order_id uuid,
  type text NOT NULL,
  title text,
  message text NOT NULL DEFAULT ''::text,
  link text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  read boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone,
  deleted_at timestamp with time zone,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT notifications_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.offer_targets (
  offer_id uuid NOT NULL,
  target_type text NOT NULL CHECK (target_type = ANY (ARRAY['product'::text, 'category'::text, 'user'::text, 'global'::text])),
  target_id uuid NOT NULL,
  CONSTRAINT offer_targets_pkey PRIMARY KEY (offer_id, target_type, target_id),
  CONSTRAINT offer_targets_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.offers(id)
);
CREATE TABLE public.offers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  seller_id uuid NOT NULL,
  code text UNIQUE,
  title text NOT NULL,
  type text NOT NULL,
  value numeric NOT NULL CHECK (value >= 0::numeric),
  scope text NOT NULL DEFAULT 'seller'::text CHECK (scope = ANY (ARRAY['seller'::text, 'platform'::text])),
  campaign_type text NOT NULL DEFAULT 'discount'::text CHECK (campaign_type = ANY (ARRAY['discount'::text, 'bogo'::text, 'flash_sale'::text, 'free_shipping'::text])),
  buy_quantity integer NOT NULL DEFAULT 0,
  get_quantity integer NOT NULL DEFAULT 0,
  min_order_value numeric NOT NULL DEFAULT 0 CHECK (min_order_value >= 0::numeric),
  max_usage integer,
  current_usage integer NOT NULL DEFAULT 0,
  is_auto_apply boolean NOT NULL DEFAULT false,
  is_flash_sale boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'expired'::text])),
  start_date timestamp with time zone NOT NULL DEFAULT now(),
  end_date timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone,
  deleted_at timestamp with time zone,
  CONSTRAINT offers_pkey PRIMARY KEY (id),
  CONSTRAINT offers_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.order_discounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  order_item_id uuid,
  offer_id uuid,
  code text,
  amount numeric NOT NULL CHECK (amount >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT order_discounts_pkey PRIMARY KEY (id),
  CONSTRAINT order_discounts_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_discounts_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id),
  CONSTRAINT order_discounts_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.offers(id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  seller_id uuid NOT NULL,
  product_id uuid,
  variant_id uuid,
  quantity integer NOT NULL CHECK (quantity > 0),
  price_at_purchase numeric NOT NULL CHECK (price_at_purchase >= 0::numeric),
  vat_rate_snapshot numeric NOT NULL DEFAULT 0,
  sku text,
  internal_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone,
  deleted_at timestamp with time zone,
  fulfillment_id uuid,
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_fulfillment_id_fkey FOREIGN KEY (fulfillment_id) REFERENCES public.fulfillments(id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_items_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.profiles(id),
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT order_items_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(id)
);
CREATE TABLE public.order_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  order_item_id uuid,
  seller_id uuid,
  created_by uuid,
  visibility text NOT NULL DEFAULT 'seller'::text CHECK (visibility = ANY (ARRAY['seller'::text, 'admin'::text, 'internal'::text])),
  note text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT order_notes_pkey PRIMARY KEY (id),
  CONSTRAINT order_notes_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_notes_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id),
  CONSTRAINT order_notes_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.profiles(id),
  CONSTRAINT order_notes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  shipping_address_id uuid,
  shipping_address_snap jsonb NOT NULL DEFAULT '{}'::jsonb,
  subtotal numeric NOT NULL DEFAULT 0 CHECK (subtotal >= 0::numeric),
  delivery_fee numeric NOT NULL DEFAULT 0 CHECK (delivery_fee >= 0::numeric),
  discount_amount numeric NOT NULL DEFAULT 0 CHECK (discount_amount >= 0::numeric),
  vat_amount numeric NOT NULL DEFAULT 0 CHECK (vat_amount >= 0::numeric),
  total numeric NOT NULL CHECK (total >= 0::numeric),
  status text NOT NULL DEFAULT 'pending',
  payment_method text,
  payment_ref text,
  customer_notes text,
  preferred_delivery_date timestamp with time zone,
  delivery_slot text,
  cancel_reason text,
  reject_reason text,
  driver_phone text,
  is_gift boolean NOT NULL DEFAULT false,
  gift_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone,
  deleted_at timestamp with time zone,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT orders_shipping_address_id_fkey FOREIGN KEY (shipping_address_id) REFERENCES public.addresses(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  currency text NOT NULL DEFAULT 'TZS'::text,
  method text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  transaction_id text,
  payment_gateway text,
  phone_used text,
  paid_at timestamp with time zone,
  refunded_at timestamp with time zone,
  refund_amount numeric NOT NULL DEFAULT 0 CHECK (refund_amount >= 0::numeric),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.platform_settings (
  key text NOT NULL,
  value jsonb NOT NULL,
  data_type text NOT NULL DEFAULT 'string'::text CHECK (data_type = ANY (ARRAY['string'::text, 'number'::text, 'boolean'::text, 'json'::text])),
  category text NOT NULL DEFAULT 'general'::text CHECK (category = ANY (ARRAY['general'::text, 'finance'::text, 'delivery'::text, 'features'::text, 'notifications'::text, 'seller'::text])),
  label text,
  description text,
  is_public boolean NOT NULL DEFAULT false,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT platform_settings_pkey PRIMARY KEY (key),
  CONSTRAINT platform_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.product_variants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  sku text UNIQUE,
  attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
  base_price numeric NOT NULL CHECK (base_price >= 0::numeric),
  price numeric NOT NULL DEFAULT 0 CHECK (price >= 0::numeric),
  sale_price numeric CHECK (sale_price >= 0::numeric),
  cost_price numeric NOT NULL DEFAULT 0,
  vat_rate numeric NOT NULL DEFAULT 0 CHECK (vat_rate >= 0::numeric AND vat_rate <= 1::numeric),
  stock integer NOT NULL DEFAULT 0 CHECK (stock >= 0),
  low_stock_threshold integer NOT NULL DEFAULT 5,
  min_stock integer NOT NULL DEFAULT 0,
  weight numeric NOT NULL DEFAULT 0,
  image_url text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone,
  deleted_at timestamp with time zone,
  CONSTRAINT product_variants_pkey PRIMARY KEY (id),
  CONSTRAINT product_variants_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  seller_id uuid NOT NULL,
  category_id uuid,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  brand text,
  sku text UNIQUE,
  barcode text,
  price numeric NOT NULL DEFAULT 0 CHECK (price >= 0::numeric),
  base_price numeric NOT NULL DEFAULT 0 CHECK (base_price >= 0::numeric),
  sale_price numeric CHECK (sale_price >= 0::numeric),
  cost_price numeric NOT NULL DEFAULT 0 CHECK (cost_price >= 0::numeric),
  vat_rate numeric NOT NULL DEFAULT 0 CHECK (vat_rate >= 0::numeric AND vat_rate <= 1::numeric),
  stock integer NOT NULL DEFAULT 0 CHECK (stock >= 0),
  low_stock_threshold integer NOT NULL DEFAULT 5,
  weight numeric NOT NULL DEFAULT 0,
  length numeric NOT NULL DEFAULT 0,
  width numeric NOT NULL DEFAULT 0,
  height numeric NOT NULL DEFAULT 0,
  images ARRAY NOT NULL DEFAULT '{}'::text[],
  tags ARRAY NOT NULL DEFAULT '{}'::text[],
  attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'out_of_stock'::text])),
  is_boosted boolean NOT NULL DEFAULT false,
  rating numeric NOT NULL DEFAULT 0 CHECK (rating >= 0::numeric AND rating <= 5::numeric),
  review_count integer NOT NULL DEFAULT 0 CHECK (review_count >= 0),
  sort_order integer NOT NULL DEFAULT 0,
  search_vector tsvector,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone,
  deleted_at timestamp with time zone,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.profiles(id),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text,
  phone text,
  avatar_url text,
  role text NOT NULL DEFAULT 'buyer',
  wallet_balance numeric NOT NULL DEFAULT 0 CHECK (wallet_balance >= 0::numeric),
  points integer NOT NULL DEFAULT 0 CHECK (points >= 0),
  tier text NOT NULL DEFAULT 'Bronze'::text CHECK (tier = ANY (ARRAY['Bronze'::text, 'Silver'::text, 'Gold'::text, 'Platinum'::text])),
  region text NOT NULL DEFAULT 'Dar es Salaam'::text,
  referral_code text UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone,
  deleted_at timestamp with time zone,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.referral_rewards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  referral_id uuid NOT NULL,
  profile_id uuid NOT NULL,
  reward_type text NOT NULL CHECK (reward_type = ANY (ARRAY['wallet_credit'::text, 'points'::text, 'discount'::text])),
  reward_value numeric NOT NULL CHECK (reward_value > 0::numeric),
  wallet_tx_id uuid,
  offer_id uuid,
  issued_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT referral_rewards_pkey PRIMARY KEY (id),
  CONSTRAINT referral_rewards_referral_id_fkey FOREIGN KEY (referral_id) REFERENCES public.referrals(id),
  CONSTRAINT referral_rewards_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT referral_rewards_wallet_tx_id_fkey FOREIGN KEY (wallet_tx_id) REFERENCES public.wallet_transactions(id),
  CONSTRAINT referral_rewards_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.offers(id)
);
CREATE TABLE public.referrals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  referrer_id uuid NOT NULL,
  referee_id uuid NOT NULL UNIQUE,
  referral_code text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  qualifying_order_id uuid,
  qualified_at timestamp with time zone,
  referrer_reward_type text DEFAULT 'wallet_credit'::text CHECK (referrer_reward_type = ANY (ARRAY['wallet_credit'::text, 'points'::text, 'discount'::text])),
  referrer_reward_value numeric NOT NULL DEFAULT 0,
  referee_reward_type text DEFAULT 'discount'::text CHECK (referee_reward_type = ANY (ARRAY['wallet_credit'::text, 'points'::text, 'discount'::text])),
  referee_reward_value numeric NOT NULL DEFAULT 0,
  rewarded_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT referrals_pkey PRIMARY KEY (id),
  CONSTRAINT referrals_referrer_id_fkey FOREIGN KEY (referrer_id) REFERENCES public.profiles(id),
  CONSTRAINT referrals_referee_id_fkey FOREIGN KEY (referee_id) REFERENCES public.profiles(id),
  CONSTRAINT referrals_qualifying_order_id_fkey FOREIGN KEY (qualifying_order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.returns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  order_item_id uuid,
  seller_id uuid,
  reason text,
  status text NOT NULL DEFAULT 'requested',
  refund_amount numeric NOT NULL DEFAULT 0 CHECK (refund_amount >= 0::numeric),
  restock_quantity integer NOT NULL DEFAULT 0,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  requested_at timestamp with time zone NOT NULL DEFAULT now(),
  processed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT returns_pkey PRIMARY KEY (id),
  CONSTRAINT returns_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT returns_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id),
  CONSTRAINT returns_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  product_id uuid NOT NULL,
  order_item_id uuid,
  rating smallint NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  images ARRAY NOT NULL DEFAULT '{}'::text[],
  is_verified_purchase boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT reviews_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id)
);
CREATE TABLE public.seller_payouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  seller_id uuid NOT NULL,
  period date NOT NULL,
  total_sales numeric NOT NULL DEFAULT 0 CHECK (total_sales >= 0::numeric),
  commission_rate numeric NOT NULL DEFAULT 0 CHECK (commission_rate >= 0::numeric AND commission_rate <= 1::numeric),
  commission_amount numeric NOT NULL DEFAULT 0 CHECK (commission_amount >= 0::numeric),
  refunds_amount numeric NOT NULL DEFAULT 0 CHECK (refunds_amount >= 0::numeric),
  fees_amount numeric NOT NULL DEFAULT 0 CHECK (fees_amount >= 0::numeric),
  net_payout numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'paid'::text, 'failed'::text])),
  paid_at timestamp with time zone,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT seller_payouts_pkey PRIMARY KEY (id),
  CONSTRAINT seller_payouts_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.shipment_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_id uuid NOT NULL,
  fulfillment_id uuid,
  status text NOT NULL CHECK (status = ANY (ARRAY['created'::text, 'picked_up'::text, 'at_sorting_hub'::text, 'out_for_delivery'::text, 'delivery_attempted'::text, 'delivered'::text, 'returned_to_sender'::text, 'cancelled'::text])),
  location text,
  latitude numeric,
  longitude numeric,
  notes text,
  occurred_at timestamp with time zone NOT NULL DEFAULT now(),
  recorded_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT shipment_events_pkey PRIMARY KEY (id),
  CONSTRAINT shipment_events_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id),
  CONSTRAINT shipment_events_fulfillment_id_fkey FOREIGN KEY (fulfillment_id) REFERENCES public.fulfillments(id),
  CONSTRAINT shipment_events_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.shipment_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_id uuid NOT NULL,
  order_item_id uuid NOT NULL,
  product_id uuid,
  variant_id uuid,
  quantity integer NOT NULL CHECK (quantity > 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT shipment_items_pkey PRIMARY KEY (id),
  CONSTRAINT shipment_items_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id),
  CONSTRAINT shipment_items_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id),
  CONSTRAINT shipment_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT shipment_items_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(id)
);
CREATE TABLE public.shipments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  seller_id uuid,
  tracking_number text,
  carrier text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in_transit'::text, 'delivered'::text, 'returned'::text, 'cancelled'::text])),
  estimated_delivery timestamp with time zone,
  shipped_at timestamp with time zone,
  actual_delivery timestamp with time zone,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT shipments_pkey PRIMARY KEY (id),
  CONSTRAINT shipments_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT shipments_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.social_interactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL,
  user_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['like'::text, 'share'::text, 'comment'::text, 'save'::text, 'click_product'::text])),
  comment_text text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT social_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT social_interactions_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.social_posts(id),
  CONSTRAINT social_interactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.social_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  product_id uuid,
  variant_id uuid,
  image_url text NOT NULL,
  caption text,
  region text NOT NULL DEFAULT 'Dar es Salaam'::text,
  is_shop_post boolean NOT NULL DEFAULT false,
  shop_link_text text,
  likes integer NOT NULL DEFAULT 0 CHECK (likes >= 0),
  shares integer NOT NULL DEFAULT 0 CHECK (shares >= 0),
  comments_count integer NOT NULL DEFAULT 0 CHECK (comments_count >= 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT social_posts_pkey PRIMARY KEY (id),
  CONSTRAINT social_posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT social_posts_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT social_posts_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(id)
);
CREATE TABLE public.trust_badges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entity_type text NOT NULL CHECK (entity_type = ANY (ARRAY['seller'::text, 'buyer'::text, 'product'::text, 'platform'::text])),
  entity_id uuid NOT NULL,
  badge_type text NOT NULL,
  badge_name text NOT NULL,
  badge_url text,
  issued_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT trust_badges_pkey PRIMARY KEY (id)
);
CREATE TABLE public.vendor_profiles (
  seller_id uuid NOT NULL,
  store_name text NOT NULL,
  description text,
  logo_url text,
  banner_url text,
  region text NOT NULL DEFAULT 'Dar es Salaam'::text,
  contact_phone text,
  default_address_id uuid,
  delivery_fee numeric NOT NULL DEFAULT 0 CHECK (delivery_fee >= 0::numeric),
  delivery_radius_km numeric,
  bank_name text,
  bank_account_name text,
  account_number text,
  tin_number text,
  business_reg_no text,
  mobile_operator text,
  mobile_number text,
  mobile_name text,
  is_verified boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  verification_level text DEFAULT 'none'::text CHECK (verification_level = ANY (ARRAY['none'::text, 'basic'::text, 'verified'::text, 'premium'::text])),
  verified_at timestamp with time zone,
  verification_badge_url text,
  trust_score numeric DEFAULT 0 CHECK (trust_score >= 0::numeric AND trust_score <= 100::numeric),
  avg_response_minutes integer DEFAULT 60,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone,
  CONSTRAINT vendor_profiles_pkey PRIMARY KEY (seller_id),
  CONSTRAINT vendor_profiles_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.profiles(id),
  CONSTRAINT vendor_profiles_default_address_id_fkey FOREIGN KEY (default_address_id) REFERENCES public.addresses(id)
);
CREATE TABLE public.wallet_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  order_id uuid,
  amount numeric NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['credit'::text, 'debit'::text, 'refund'::text, 'payout'::text, 'adjustment'::text])),
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT wallet_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT wallet_transactions_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT wallet_transactions_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);